apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapp
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: git@github.com:goelshubham/argocd-app-config.git
      revision: main
      files:
      - path: "cluster-configs/ingest/stage/us-west-2/shard-0.yaml"
  template:
    metadata:
      name: myapp
    spec:
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      project: default
      source:
        repoURL: git@github.com:goelshubham/argocd-app-config.git
        targetRevision: HEAD
        path: kube/myapp
      destination:
        name: https://kubernetes.default.svc
        namespace: argocd

