apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapp-applicationset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: kind-k2-test
            url: https://kubernetes.default.svc
  template:
    metadata:
      name: myapp
    spec:
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      project: default
      source:
        repoURL: https://github.com/goelshubham/argocd-app-config.git
        targetRevision: HEAD
        path: kube/myapp
      destination:
        name: kind-k2-test
        namespace: argocd

