apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp4-deployment
spec:
  selector:
    matchLabels:
      app: myapp4
  replicas: 4
  template:
    metadata:
      labels:
        app: myapp4
    spec:
      containers:
      - name: myapp4
        image: nanajanashia/argocd-app:1.2
        ports:
        - containerPort: 8080
