apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-cmp-1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    path: unknown-manifest
    targetRevision: guestbook
    plugin:
      name: cmp-plugin
      env:
      - name: FOO
        value: bar
  destination:
    server: https://kubernetes.default.svc
    namespace: default