apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-cmp-1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/goelshubham/argocd-app-config.git
    path: guestbook
    targetRevision: HEAD
    plugin:
      env:
      - name: FOO
        value: bar
  destination:
    server: https://kubernetes.default.svc
    namespace: default