apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-cmp-1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/goelshubham/argocd-app-config.git
    path: kube/myapp3
    targetRevision: HEAD
    plugin: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: default