apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapp3-appset
  namespace: argocd
spec:
  generators:
    - git: # generated parameters based on files or folders within a git repo
        repoURL: https://github.com/goelshubham/argocd-app-config.git
        revision: HEAD # points to which branch, tag, build of repo
        files:
          - path: "shard-configs/ingest/**/shard-*.yaml"
  template:
    metadata:
      name: '{{namespace}}-myapp3'
    spec:
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      project: default
      source:
        repoURL: tracking-api repo # mono-repo
        targetRevision: HEAD
        path: # path to k2 file
        plugin:
          name: cmp-plugin
          env:
            - name: image  # {{argocd_env_image}}
              value: "{{config.image}}"  # dynamic parameter passed from shard config files
            - name: replicas
              value: "{{config.replicas}}"
            - name: targetGroupARN
              value: "{{config.targetGroupARN}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'

