apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapp4-appset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/goelshubham/argocd-app-config.git
        revision: HEAD
        files:
          - path: "shard-configs/ingest/**/shard-*.yaml"
  template:
    metadata:
      name: '{{namespace}}-myapp4'
    spec:
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      project: default
      source:
        repoURL: https://github.com/nginxinc/kubernetes-ingress
        targetRevision: v2.2.2
        path: deployments/helm-chart
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'

