apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapp3-appset
  namespace: argocd
spec:
  generators:
    - git: # generated parameters based on files or folders within a git repo
        repoURL: https://github.com/goelshubham/argocd-app-config.git
        revision: HEAD # points to which branch, tag, build of repo
        files:
          - path: "shard-configs/ingest/**/shard-*.yaml"
  template:
    metadata:
      name: '{{namespace}}-myapp3'
    spec:
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      project: default
      source:
        repoURL: https://github.com/goelshubham/argocd-app-config.git
        targetRevision: HEAD
        path: .k2
        plugin:
          name: cmp-plugin
          env:
            - name: image
              value: nginx:1.14.2
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'

