apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapp3-appset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/goelshubham/argocd-app-config.git
        revision: HEAD
        files:
          - path: "shard-configs/ingest/**/shard-*.yaml"
  template:
    metadata:
      name: '{{namespace}}-myapp3'
    spec:
      syncPolicy:
        - CreateNamespace=true
      automated:
        prune: true
        selfHeal: true
      project: default
      source:
        repoURL: https://github.com/goelshubham/argocd-app-config.git
        targetRevision: HEAD
        path: kube/myapp3
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'

