apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rootapp-2
  namespace: argocd
spec:
  project: default
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: application-set2  # This is the path where the application set of each individual app can be found
    repoURL: https://github.com/goelshubham/argocd-app-config.git
    targetRevision: HEAD
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
